#!/bin/bash

# get terminal codes for colors, bold, and normal text
bold=$(tput bold)
normal=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)

# set terminal name
NAME="git pre-push hook"; echo -en "\033]0;$NAME\a"

# this script reassembles the Recipes.pdf before every push

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

# get the top-level directory for the repo
GITROOT="$(git rev-parse --show-toplevel)"

DIR="$PWD"

# let the user know what's going on
echo "Compiling Recipes.pdf before push.
You can skip this by using
git push <remote> <branch> --no-verify"

# temporarily move to GITROOT
cd "$GITROOT"

while true; do

    ./compile.sh -a

    returncode=$?

    if [ "$returncode" -eq 0 ]
    then
        echo "${bold}${red}There are changes to Recipes.pdf, \
please commit them before pushing.${normal}"
        echo "$(git status)"
        read -p "${green}Would you like to automatically commit all of them \
now? [y/n] ${normal}" -n 1 -r
        echo

        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            read -p "Commit description: " desc
            git commit -a -m "$desc"
        else
            echo "Aborting push."
            exit 1
        fi
    else
        echo "${green}${bold}Recipes.pdf up to date. Ready for push.${normal}"
        break
    fi

done

# move back to where the script was originally ran
cd "$DIR"

# check to see if evince and wmctrl are installed

if command -v evince > /dev/null 2>&1 && \
    command -v wmctrl > /dev/null 2>&1 ; then
    evince "$GITROOT/Recipes.pdf" &
    PDF_PID=$!
    sleep 0.5
    wmctrl -a "git pre-push hook"
else
    xdg-open "$GITROOT/Recipes.pdf" &
    PDF_PID=$!
fi

read -p "Please review the PDF and confirm it is correct. [y/n] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    kill "$PDF_PID" > /dev/null 2>&1
    echo "Push confirmed."
    exit 0
else
    kill ${PDF_PID} > /dev/null 2>&1
    echo "Push cancelled."
    exit 1
fi


